#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM quay.io/ascend/vllm-ascend:v0.18.0-310p-openeuler

ARG PIP_INDEX_URL="https://mirrors.aliyun.com/pypi/simple"
ARG PIP_NO_CACHE_DIR=1

ENV SOC_VERSION=Ascend310P3
ENV LMCACHE_TRACK_USAGE=false

WORKDIR /workspace

COPY . /workspace/LMCache-Ascend/

# Install LMCache && LMCache-Ascend
RUN NO_CUDA_EXT=1 pip install lmcache==0.4.2 && \
    cd /workspace/LMCache-Ascend && \
    export CPLUS_INCLUDE_PATH=/usr/include/c++/12:/usr/include/c++/12/`uname -i`-openEuler-linux:$CPLUS_INCLUDE_PATH && \
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Ascend/ascend-toolkit/latest/`uname -i`-linux/devlib && \
    pip install -v --no-build-isolation -e .

CMD ["/bin/bash"]
